name: triawan_cafe_resto_app
description: "A modern and responsive cafe restaurant Flutter app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  # ğŸ§© State Management
  provider: ^6.1.2

  # ğŸŒ HTTP Request untuk koneksi API
  http: ^1.2.2

  # ğŸ“± Icon iOS-style
  cupertino_icons: ^1.0.8

  # ğŸ’… Modern UI components & animation (optional tapi bikin keren)
  google_fonts: ^6.1.0
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/images/banner1.jpeg
    - assets/images/banner2.jpeg
    - assets/images/banner3.jpeg
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/onboard1.png"